### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mwisnicki** [guizmaii-opensource/sbt-datadog#126]
Why was the license removed?

**Comment by guizmaii** [comment]
What do you mean? @mwisnicki

**Comment by mwisnicki** [comment]
https://github.com/guizmaii-opensource/sbt-datadog/pull/1/files#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

**Comment by mwisnicki** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license

**Comment by guizmaii** [comment]
Hum. Mistake. The project is clearly under MIT licence. I'll put it back. Thanks

**Comment by guizmaii** [comment]
It's back https://github.com/guizmaii-opensource/sbt-datadog/blob/main/LICENSE

**Comment by mwisnicki** [comment]
In that case you'll probably want to update [build.sbt](https://github.com/guizmaii-opensource/sbt-datadog/blob/a370a14b14bf669a11f839e54f495b769148ba9c/build.sbt#L12) because it currently says Apache-2.
